module v12

import protocol
import version.v12.packets
import version.v11.packets as packets_11
import version.v9.packets as packets_9

pub fn new_pool() protocol.PacketPool {
	mut pool := protocol.new_empty_pool()
	pool.register(|| protocol.Packet(&packets_11.PingPacket{}))
	pool.register(|| protocol.Packet(&packets_11.PongPacket{}))
	pool.register(|| protocol.Packet(&packets_9.ClientConnectPacket{}))
	pool.register(|| protocol.Packet(&packets_11.ServerHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets_9.ClientHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets_11.ServerFullPacket{}))
	pool.register(|| protocol.Packet(&packets_9.DisconnectPacket{}))
	pool.register(|| protocol.Packet(&packets_11.BannedPacket{}))
	pool.register(|| protocol.Packet(&packets_11.LoginPacket{}))
	pool.register(|| protocol.Packet(&packets_9.PlayStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_9.ReadyPacket{}))
	pool.register(|| protocol.Packet(&packets.MessagePacket{}))
	pool.register(|| protocol.Packet(&packets.SetTimePacket{}))
	pool.register(|| protocol.Packet(&packets_9.StartGamePacket{}))
	pool.register(|| protocol.Packet(&packets.AddMobPacket{}))
	pool.register(|| protocol.Packet(&packets.AddPlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_11.RemovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_11.AddEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.RemoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.AddItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_11.TakeItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.MoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.MoveEntityPosRotPacket{}))
	pool.register(|| protocol.Packet(&packets_9.MovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_9.PlaceBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_9.RemoveBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_9.UpdateBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_11.AddPaintingPacket{}))
	pool.register(|| protocol.Packet(&packets_11.ExplosionPacket{}))
	pool.register(|| protocol.Packet(&packets_11.LevelEventPacket{}))
	pool.register(|| protocol.Packet(&packets.TileEventPacket{}))
	pool.register(|| protocol.Packet(&packets_11.EntityEventPacket{}))
	pool.register(|| protocol.Packet(&packets_9.RequestChunkPacket{}))
	pool.register(|| protocol.Packet(&packets_9.ChunkDataPacket{}))
	pool.register(|| protocol.Packet(&packets_11.PlayerEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_11.PlayerArmorEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_11.InteractPacket{}))
	pool.register(|| protocol.Packet(&packets_11.UseItemPacket{}))
	pool.register(|| protocol.Packet(&packets_11.PlayerActionPacket{}))
	pool.register(|| protocol.Packet(&packets_11.HurtArmorPacket{}))
	pool.register(|| protocol.Packet(&packets_11.SetEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_11.SetEntityMotionPacket{}))
	pool.register(|| protocol.Packet(&packets_11.SetHealthPacket{}))
	pool.register(|| protocol.Packet(&packets_11.SetSpawnPositionPacket{}))
	pool.register(|| protocol.Packet(&packets_11.AnimatePacket{}))
	pool.register(|| protocol.Packet(&packets_11.RespawnPacket{}))
	pool.register(|| protocol.Packet(&packets_11.SendInventoryPacket{}))
	pool.register(|| protocol.Packet(&packets_11.DropItemPacket{}))
	pool.register(|| protocol.Packet(&packets.ContainerOpenPacket{}))
	pool.register(|| protocol.Packet(&packets_11.ContainerClosePacket{}))
	pool.register(|| protocol.Packet(&packets_11.ContainerSetSlotPacket{}))
	pool.register(|| protocol.Packet(&packets_11.ContainerSetDataPacket{}))
	pool.register(|| protocol.Packet(&packets_11.ContainerSetContentPacket{}))
	pool.register(|| protocol.Packet(&packets_11.ClientMessagePacket{}))
	pool.register(|| protocol.Packet(&packets.AdventureSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets.EntityDataPacket{}))
	return pool
}
