module v60

import protocol
import protocol.version.v60.packets
import protocol.version.v45.packets as packets_45
import protocol.version.v38.packets as packets_38
import protocol.version.v34.packets as packets_34

pub fn new_pool() protocol.PacketPool {
	mut pool := protocol.new_empty_pool()
	pool.register(|| protocol.Packet(&packets_45.LoginPacket{}))
	pool.register(|| protocol.Packet(&packets_34.PlayStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_34.DisconnectPacket{}))
	pool.register(|| protocol.Packet(&packets_34.TextPacket{}))
	pool.register(|| protocol.Packet(&packets_34.SetTimePacket{}))
	pool.register(|| protocol.Packet(&packets.StartGamePacket{}))
	pool.register(|| protocol.Packet(&packets_34.AddPlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_34.RemovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_34.AddEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_34.RemoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_34.AddItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_34.TakeItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_34.MoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_34.MovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_34.RemoveBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_34.UpdateBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_34.AddPaintingPacket{}))
	pool.register(|| protocol.Packet(&packets_34.ExplodePacket{}))
	pool.register(|| protocol.Packet(&packets_34.LevelEventPacket{}))
	pool.register(|| protocol.Packet(&packets_38.BlockEventPacket{}))
	pool.register(|| protocol.Packet(&packets_34.EntityEventPacket{}))
	pool.register(|| protocol.Packet(&packets_34.MobEffectPacket{}))
	pool.register(|| protocol.Packet(&packets_34.UpdateAttributesPacket{}))
	pool.register(|| protocol.Packet(&packets_34.MobEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_34.MobArmorEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_34.InteractPacket{}))
	pool.register(|| protocol.Packet(&packets_34.UseItemPacket{}))
	pool.register(|| protocol.Packet(&packets_34.PlayerActionPacket{}))
	pool.register(|| protocol.Packet(&packets_34.HurtArmorPacket{}))
	pool.register(|| protocol.Packet(&packets_34.SetEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_34.SetEntityMotionPacket{}))
	pool.register(|| protocol.Packet(&packets_34.SetEntityLinkPacket{}))
	pool.register(|| protocol.Packet(&packets_34.SetHealthPacket{}))
	pool.register(|| protocol.Packet(&packets_34.SetSpawnPositionPacket{}))
	pool.register(|| protocol.Packet(&packets_34.AnimatePacket{}))
	pool.register(|| protocol.Packet(&packets_34.RespawnPacket{}))
	pool.register(|| protocol.Packet(&packets_34.DropItemPacket{}))
	pool.register(|| protocol.Packet(&packets_34.ContainerOpenPacket{}))
	pool.register(|| protocol.Packet(&packets_34.ContainerClosePacket{}))
	pool.register(|| protocol.Packet(&packets_38.ContainerSetSlotPacket{}))
	pool.register(|| protocol.Packet(&packets_34.ContainerSetDataPacket{}))
	pool.register(|| protocol.Packet(&packets_34.ContainerSetContentPacket{}))
	pool.register(|| protocol.Packet(&packets_34.CraftingDataPacket{}))
	pool.register(|| protocol.Packet(&packets_34.CraftingEventPacket{}))
	pool.register(|| protocol.Packet(&packets.AdventureSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_38.BlockEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_34.FullChunkDataPacket{}))
	pool.register(|| protocol.Packet(&packets_34.SetDifficultyPacket{}))
	pool.register(|| protocol.Packet(&packets.RequestChunkRadiusPacket{}))
	pool.register(|| protocol.Packet(&packets.ChunkRadiusUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets_45.SetPlayerGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets_45.PlayerListPacket{}))
	return pool
}
