module protocol


pub struct PacketPool {
pub mut:
	factories map[u16]fn () Packet
}

pub fn new_packet_pool() PacketPool {
	mut p := PacketPool{
		factories: map[u16]fn () Packet{}
	}
	p.register(|| Packet(&LoginPacket{}))
	p.register(|| Packet(&PlayStatusPacket{}))
	p.register(|| Packet(&ServerToClientHandshakePacket{}))
	p.register(|| Packet(&ClientToServerHandshakePacket{}))
	p.register(|| Packet(&DisconnectPacket{}))
	p.register(|| Packet(&SetTimePacket{}))
	p.register(|| Packet(&TextPacket{}))
	p.register(|| Packet(&RequestNetworkSettingsPacket{}))
	p.register(|| Packet(&NetworkSettingsPacket{}))
	p.register(|| Packet(&RequestChunkRadiusPacket{}))
	p.register(|| Packet(&ChunkRadiusUpdatedPacket{}))
	p.register(|| Packet(&SetLocalPlayerAsInitializedPacket{}))
	p.register(|| Packet(&RespawnPacket{}))
	p.register(|| Packet(&AnimatePacket{}))
	p.register(|| Packet(&ContainerClosePacket{}))
	p.register(|| Packet(&ClientCacheStatusPacket{}))
	p.register(|| Packet(&SetDifficultyPacket{}))
	p.register(|| Packet(&NetworkStackLatencyPacket{}))
	p.register(|| Packet(&InteractPacket{}))
	p.register(|| Packet(&EmotePacket{}))
	p.register(|| Packet(&PlayerActionPacket{}))
	p.register(|| Packet(&ResourcePackClientResponsePacket{}))
	p.register(|| Packet(&ResourcePackChunkRequestPacket{}))
	p.register(|| Packet(&ResourcePackDataInfoPacket{}))
	p.register(|| Packet(&ResourcePackChunkDataPacket{}))
	p.register(|| Packet(&RemoveActorPacket{}))
	p.register(|| Packet(&TakeItemActorPacket{}))
	p.register(|| Packet(&SetActorMotionPacket{}))
	p.register(|| Packet(&MoveActorAbsolutePacket{}))
	p.register(|| Packet(&SetHealthPacket{}))
	p.register(|| Packet(&SetSpawnPositionPacket{}))
	p.register(|| Packet(&ShowCreditsPacket{}))
	p.register(|| Packet(&BlockPickRequestPacket{}))
	p.register(|| Packet(&ActorPickRequestPacket{}))
	p.register(|| Packet(&SetPlayerGameTypePacket{}))
	p.register(|| Packet(&SpawnExperienceOrbPacket{}))
	p.register(|| Packet(&OnScreenTextureAnimationPacket{}))
	p.register(|| Packet(&SimpleEventPacket{}))
	p.register(|| Packet(&RefreshEntitlementsPacket{}))
	p.register(|| Packet(&TickingAreasLoadStatusPacket{}))
	p.register(|| Packet(&PlayerHotbarPacket{}))
	p.register(|| Packet(&GuiDataPickItemPacket{}))
	p.register(|| Packet(&HurtArmorPacket{}))
	p.register(|| Packet(&MobEquipmentPacket{}))
	p.register(|| Packet(&MobArmorEquipmentPacket{}))
	p.register(|| Packet(&InventorySlotPacket{}))
	p.register(|| Packet(&InventoryContentPacket{}))
	p.register(|| Packet(&ContainerOpenPacket{}))
	p.register(|| Packet(&ContainerSetDataPacket{}))
	p.register(|| Packet(&CreativeContentPacket{}))
	p.register(|| Packet(&BlockActorDataPacket{}))
	p.register(|| Packet(&ItemRegistryPacket{}))
	p.register(|| Packet(&UpdateEquipPacket{}))
	p.register(|| Packet(&SetActorDataPacket{}))
	p.register(|| Packet(&AddItemActorPacket{}))
	p.register(|| Packet(&MobEffectPacket{}))
	p.register(|| Packet(&MovePlayerPacket{}))
	p.register(|| Packet(&AddActorPacket{}))
	p.register(|| Packet(&UpdateAttributesPacket{}))
	p.register(|| Packet(&ChangeDimensionPacket{}))
	p.register(|| Packet(&SetCommandsEnabledPacket{}))
	p.register(|| Packet(&UpdateBlockPacket{}))
	p.register(|| Packet(&BlockEventPacket{}))
	p.register(|| Packet(&ActorEventPacket{}))
	p.register(|| Packet(&SetActorLinkPacket{}))
	p.register(|| Packet(&NetworkChunkPublisherUpdatePacket{}))
	p.register(|| Packet(&GameRulesChangedPacket{}))
	p.register(|| Packet(&SettingsCommandPacket{}))
	p.register(|| Packet(&UpdateSoftEnumPacket{}))
	p.register(|| Packet(&ModalFormRequestPacket{}))
	p.register(|| Packet(&ModalFormResponsePacket{}))
	p.register(|| Packet(&ServerSettingsRequestPacket{}))
	p.register(|| Packet(&ServerSettingsResponsePacket{}))
	p.register(|| Packet(&RemoveObjectivePacket{}))
	p.register(|| Packet(&ToastRequestPacket{}))
	p.register(|| Packet(&SetTitlePacket{}))
	p.register(|| Packet(&SetDisplayObjectivePacket{}))
	p.register(|| Packet(&NpcDialoguePacket{}))
	p.register(|| Packet(&LevelEventPacket{}))
	p.register(|| Packet(&StopSoundPacket{}))
	p.register(|| Packet(&PlaySoundPacket{}))
	p.register(|| Packet(&SpawnParticleEffectPacket{}))
	p.register(|| Packet(&PlayerFogPacket{}))
	p.register(|| Packet(&CameraShakePacket{}))
	p.register(|| Packet(&AddPaintingPacket{}))
	p.register(|| Packet(&TransferPacket{}))
	p.register(|| Packet(&OpenSignPacket{}))
	p.register(|| Packet(&AnvilDamagePacket{}))
	p.register(|| Packet(&PlayerStartItemCooldownPacket{}))
	p.register(|| Packet(&ClientboundCloseFormPacket{}))
	p.register(|| Packet(&ScriptMessagePacket{}))
	p.register(|| Packet(&SimulationTypePacket{}))
	p.register(|| Packet(&DeathInfoPacket{}))
	p.register(|| Packet(&AwardAchievementPacket{}))
	p.register(|| Packet(&LevelSoundEventPacket{}))
	p.register(|| Packet(&AnimateEntityPacket{}))
	p.register(|| Packet(&MotionPredictionHintsPacket{}))
	p.register(|| Packet(&NpcRequestPacket{}))
	p.register(|| Packet(&CompletedUsingItemPacket{}))
	p.register(|| Packet(&MoveActorDeltaPacket{}))
	p.register(|| Packet(&SetLastHurtByPacket{}))
	p.register(|| Packet(&CurrentStructureFeaturePacket{}))
	p.register(|| Packet(&ServerboundLoadingScreenPacket{}))
	p.register(|| Packet(&PlayerToggleCrafterSlotRequestPacket{}))
	p.register(|| Packet(&SetDefaultGameTypePacket{}))
	p.register(|| Packet(&UpdatePlayerGameTypePacket{}))
	p.register(|| Packet(&CodeBuilderPacket{}))
	p.register(|| Packet(&LecternUpdatePacket{}))
	p.register(|| Packet(&PurchaseReceiptPacket{}))
	p.register(|| Packet(&ShowProfilePacket{}))
	p.register(|| Packet(&RequestPermissionsPacket{}))
	p.register(|| Packet(&ClientCacheBlobStatusPacket{}))
	p.register(|| Packet(&BossEventPacket{}))
	p.register(|| Packet(&UpdateBlockSyncedPacket{}))
	p.register(|| Packet(&BookEditPacket{}))
	p.register(|| Packet(&CommandRequestPacket{}))
	p.register(|| Packet(&SetScorePacket{}))
	p.register(|| Packet(&SetScoreboardIdentityPacket{}))
	p.register(|| Packet(&ShowStoreOfferPacket{}))
	p.register(|| Packet(&AgentAnimationPacket{}))
	p.register(|| Packet(&ServerPlayerPostMovePositionPacket{}))
	p.register(|| Packet(&UpdateClientInputLocksPacket{}))
	p.register(|| Packet(&ClientboundControlSchemeSetPacket{}))
	p.register(|| Packet(&UpdateAdventureSettingsPacket{}))
	p.register(|| Packet(&MultiplayerSettingsPacket{}))
	p.register(|| Packet(&SetPlayerInventoryOptionsPacket{}))
	p.register(|| Packet(&EmoteListPacket{}))
	p.register(|| Packet(&SetHudPacket{}))
	p.register(|| Packet(&RequestAbilityPacket{}))
	p.register(|| Packet(&CodeBuilderSourcePacket{}))
	p.register(|| Packet(&GameTestRequestPacket{}))
	p.register(|| Packet(&LessonProgressPacket{}))
	p.register(|| Packet(&ServerStatsPacket{}))
	p.register(|| Packet(&PartyChangedPacket{}))
	p.register(|| Packet(&CommandBlockUpdatePacket{}))
	p.register(|| Packet(&AddBehaviorTreePacket{}))
	p.register(|| Packet(&RemoveVolumeEntityPacket{}))
	p.register(|| Packet(&SyncActorPropertyPacket{}))
	p.register(|| Packet(&ServerboundDataDrivenScreenClosedPacket{}))
	p.register(|| Packet(&PartyDestinationCookieResponsePacket{}))
	p.register(|| Packet(&SendPartyDestinationCookiePacket{}))
	p.register(|| Packet(&PlayerVideoCapturePacket{}))
	p.register(|| Packet(&UpdateClientOptionsPacket{}))
	p.register(|| Packet(&PacketViolationWarningPacket{}))
	p.register(|| Packet(&MovementEffectPacket{}))
	p.register(|| Packet(&LegacyTelemetryEventPacket{}))
	p.register(|| Packet(&CorrectPlayerMovePredictionPacket{}))
	p.register(|| Packet(&ClientboundTextureShiftPacket{}))
	p.register(|| Packet(&ChangeMobPropertyPacket{}))
	p.register(|| Packet(&UpdateTradePacket{}))
	p.register(|| Packet(&PlayerArmorDamagePacket{}))
	p.register(|| Packet(&MapInfoRequestPacket{}))
	p.register(|| Packet(&CameraPacket{}))
	p.register(|| Packet(&PlayerLocationPacket{}))
	p.register(|| Packet(&AgentActionEventPacket{}))
	p.register(|| Packet(&CreatePhotoPacket{}))
	p.register(|| Packet(&ClientCameraAimAssistPacket{}))
	p.register(|| Packet(&AutomationClientConnectPacket{}))
	p.register(|| Packet(&UnlockedRecipesPacket{}))
	p.register(|| Packet(&EditorNetworkPacket{}))
	p.register(|| Packet(&EduUriResourcePacket{}))
	p.register(|| Packet(&FeatureRegistryPacket{}))
	p.register(|| Packet(&ClientboundDataDrivenUIReloadPacket{}))
	p.register(|| Packet(&ClientboundDataDrivenUICloseScreenPacket{}))
	p.register(|| Packet(&ClientboundDataDrivenUIShowScreenPacket{}))
	p.register(|| Packet(&ResourcePacksReadyForValidationPacket{}))
	p.register(|| Packet(&ContainerRegistryCleanupPacket{}))
	p.register(|| Packet(&PlayerUpdateEntityOverridesPacket{}))
	p.register(|| Packet(&DebugInfoPacket{}))
	p.register(|| Packet(&PositionTrackingDBClientRequestPacket{}))
	p.register(|| Packet(&PositionTrackingDBServerBroadcastPacket{}))
	p.register(|| Packet(&AddVolumeEntityPacket{}))
	p.register(|| Packet(&MapCreateLockedCopyPacket{}))
	p.register(|| Packet(&StructureTemplateDataResponsePacket{}))
	p.register(|| Packet(&SubChunkRequestPacket{}))
	p.register(|| Packet(&AvailableActorIdentifiersPacket{}))
	p.register(|| Packet(&GameTestResultsPacket{}))
	p.register(|| Packet(&LabTablePacket{}))
	p.register(|| Packet(&ClientboundUpdateSoundDataPacket{}))
	p.register(|| Packet(&PhotoTransferPacket{}))
	p.register(|| Packet(&SubClientLoginPacket{}))
	p.register(|| Packet(&CameraAimAssistPacket{}))
	p.register(|| Packet(&ClientCacheMissResponsePacket{}))
	p.register(|| Packet(&UpdateAbilitiesPacket{}))
	p.register(|| Packet(&JigsawStructureDataPacket{}))
	p.register(|| Packet(&DimensionDataPacket{}))
	p.register(|| Packet(&UpdateSubChunkBlocksPacket{}))
	p.register(|| Packet(&CommandOutputPacket{}))
	p.register(|| Packet(&LevelChunkPacket{}))
	p.register(|| Packet(&TrimDataPacket{}))
	p.register(|| Packet(&ResourcePackStackPacket{}))
	p.register(|| Packet(&ResourcePacksInfoPacket{}))
	p.register(|| Packet(&StructureBlockUpdatePacket{}))
	p.register(|| Packet(&StructureTemplateDataRequestPacket{}))
	p.register(|| Packet(&SubChunkPacket{}))
	p.register(|| Packet(&PlayerEnchantOptionsPacket{}))
	p.register(|| Packet(&LocatorBarPacket{}))
	p.register(|| Packet(&GraphicsOverrideParameterPacket{}))
	p.register(|| Packet(&CameraSplinePacket{}))
	p.register(|| Packet(&CameraAimAssistActorPriorityPacket{}))
	p.register(|| Packet(&CameraInstructionPacket{}))
	p.register(|| Packet(&EducationSettingsPacket{}))
	p.register(|| Packet(&ServerboundPackSettingChangePacket{}))
	p.register(|| Packet(&ServerStoreInfoPacket{}))
	p.register(|| Packet(&ServerPresenceInfoPacket{}))
	p.register(|| Packet(&PlayerSkinPacket{}))
	p.register(|| Packet(&AddPlayerPacket{}))
	p.register(|| Packet(&PlayerListPacket{}))
	p.register(|| Packet(&ClientboundDebugRendererPacket{}))
	p.register(|| Packet(&ClientMovementPredictionSyncPacket{}))
	p.register(|| Packet(&LevelEventGenericPacket{}))
	p.register(|| Packet(&ServerboundDiagnosticsPacket{}))
	p.register(|| Packet(&ServerboundDataStorePacket{}))
	p.register(|| Packet(&SyncWorldClocksPacket{}))
	p.register(|| Packet(&ClientboundAttributeLayerSyncPacket{}))
	p.register(|| Packet(&ClientboundDataStorePacket{}))
	p.register(|| Packet(&VoxelShapesPacket{}))
	p.register(|| Packet(&PrimitiveShapesPacket{}))
	p.register(|| Packet(&CameraAimAssistPresetsPacket{}))
	p.register(|| Packet(&CameraPresetsPacket{}))
	p.register(|| Packet(&ClientboundMapItemDataPacket{}))
	p.register(|| Packet(&BiomeDefinitionListPacket{}))
	p.register(|| Packet(&ItemStackRequestPacket{}))
	p.register(|| Packet(&ItemStackResponsePacket{}))
	p.register(|| Packet(&InventoryTransactionPacket{}))
	p.register(|| Packet(&PlayerAuthInputPacket{}))
	p.register(|| Packet(&CraftingDataPacket{}))
	p.register(|| Packet(&StartGamePacket{}))
	p.register(|| Packet(&AvailableCommandsPacket{}))
	return p
}

pub fn (mut p PacketPool) register(factory fn () Packet) {
	pkt := factory()
	p.factories[pkt.pid()] = factory
}

pub fn (p &PacketPool) get_packet_by_id(pid u16) ?Packet {
	factory := p.factories[pid] or { return none }
	return factory()
}

pub fn (p &PacketPool) decode(mut r Reader) !Packet {
	header := read_packet_header(mut r)!
	mut pkt := p.get_packet_by_id(header.pid) or {
		return error('unknown packet id 0x${header.pid:x}')
	}
	pkt.decode_payload(mut r)!
	return pkt
}
