module v630

import protocol
import protocol.version
import protocol.version.v291.packets as packets_291
import protocol.version.v313.packets as packets_313
import protocol.version.v332.packets as packets_332
import protocol.version.v354.packets as packets_354
import protocol.version.v361.packets as packets_361
import protocol.version.v388.packets as packets_388
import protocol.version.v390.packets as packets_390
import protocol.version.v407.packets as packets_407
import protocol.version.v419.packets as packets_419
import protocol.version.v422.packets as packets_422
import protocol.version.v428.packets as packets_428
import protocol.version.v431.packets as packets_431
import protocol.version.v440.packets as packets_440
import protocol.version.v448.packets as packets_448
import protocol.version.v465.packets as packets_465
import protocol.version.v471.packets as packets_471
import protocol.version.v486.packets as packets_486
import protocol.version.v503.packets as packets_503
import protocol.version.v527.packets as packets_527
import protocol.version.v534.packets as packets_534
import protocol.version.v544.packets as packets_544
import protocol.version.v554.packets as packets_554
import protocol.version.v557.packets as packets_557
import protocol.version.v560.packets as packets_560
import protocol.version.v567.packets as packets_567
import protocol.version.v568.packets as packets_568
import protocol.version.v575.packets as packets_575
import protocol.version.v582.packets as packets_582
import protocol.version.v589.packets as packets_589
import protocol.version.v594.packets as packets_594
import protocol.version.v618.packets as packets_618
import protocol.version.v622.packets as packets_622
import protocol.version.v630.packets

pub const proto_version = version.ProtoVersion.v630

pub fn new_pool() protocol.PacketPool {
	mut pool := protocol.new_empty_pool()
	pool.register(|| protocol.Packet(&packets_291.AddBehaviorTreePacket{}))
	pool.register(|| protocol.Packet(&packets_560.AddEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_560.AddItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_361.AddPaintingPacket{}))
	pool.register(|| protocol.Packet(&packets_560.AddPlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_503.AddVolumeEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_291.AdventureSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_503.AgentActionEventPacket{}))
	pool.register(|| protocol.Packet(&packets_594.AgentAnimationPacket{}))
	pool.register(|| protocol.Packet(&packets_465.AnimateEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_291.AnimatePacket{}))
	pool.register(|| protocol.Packet(&packets_388.AnvilDamagePacket{}))
	pool.register(|| protocol.Packet(&packets_291.AutomationClientConnectPacket{}))
	pool.register(|| protocol.Packet(&packets_594.AvailableCommandsPacket{}))
	pool.register(|| protocol.Packet(&packets_313.AvailableEntityIdentifiersPacket{}))
	pool.register(|| protocol.Packet(&packets_313.BiomeDefinitionListPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BlockEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BlockEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BlockPickRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BookEditPacket{}))
	pool.register(|| protocol.Packet(&packets_486.BossEventPacket{}))
	pool.register(|| protocol.Packet(&packets_618.CameraInstructionPacket{}))
	pool.register(|| protocol.Packet(&packets_291.CameraPacket{}))
	pool.register(|| protocol.Packet(&packets_618.CameraPresetsPacket{}))
	pool.register(|| protocol.Packet(&packets_428.CameraShakePacket{}))
	pool.register(|| protocol.Packet(&packets_291.ChangeDimensionPacket{}))
	pool.register(|| protocol.Packet(&packets_503.ChangeMobPropertyPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ChunkRadiusUpdatedPacket{}))
	pool.register(|| protocol.Packet(&packets_361.ClientCacheBlobStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_361.ClientCacheMissResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_361.ClientCacheStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_567.ClientCheatAbilityPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ClientToServerHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets_428.ClientboundDebugRendererPacket{}))
	pool.register(|| protocol.Packet(&packets_544.ClientboundMapItemDataPacket{}))
	pool.register(|| protocol.Packet(&packets_407.CodeBuilderPacket{}))
	pool.register(|| protocol.Packet(&packets_486.CodeBuilderSourcePacket{}))
	pool.register(|| protocol.Packet(&packets_361.CommandBlockUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets_291.CommandOutputPacket{}))
	pool.register(|| protocol.Packet(&packets_567.CommandRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_388.CompletedUsingItemPacket{}))
	pool.register(|| protocol.Packet(&packets_582.CompressedBiomeDefinitionListPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ContainerClosePacket{}))
	pool.register(|| protocol.Packet(&packets_291.ContainerOpenPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ContainerSetDataPacket{}))
	pool.register(|| protocol.Packet(&packets_419.CorrectPlayerMovePredictionPacket{}))
	pool.register(|| protocol.Packet(&packets_582.CraftingDataPacket{}))
	pool.register(|| protocol.Packet(&packets_291.CraftingEventPacket{}))
	pool.register(|| protocol.Packet(&packets_465.CreatePhotoPacket{}))
	pool.register(|| protocol.Packet(&packets_431.CreativeContentPacket{}))
	pool.register(|| protocol.Packet(&packets_534.DeathInfoPacket{}))
	pool.register(|| protocol.Packet(&packets_407.DebugInfoPacket{}))
	pool.register(|| protocol.Packet(&packets_503.DimensionDataPacket{}))
	pool.register(|| protocol.Packet(&packets_622.DisconnectPacket{}))
	pool.register(|| protocol.Packet(&packets_534.EditorNetworkPacket{}))
	pool.register(|| protocol.Packet(&packets_465.EduUriResourcePacket{}))
	pool.register(|| protocol.Packet(&packets_465.EducationSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_407.EmoteListPacket{}))
	pool.register(|| protocol.Packet(&packets_589.EmotePacket{}))
	pool.register(|| protocol.Packet(&packets_534.EntityEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.EntityFallPacket{}))
	pool.register(|| protocol.Packet(&packets_465.EntityPickRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_589.EventPacket{}))
	pool.register(|| protocol.Packet(&packets_544.FeatureRegistryPacket{}))
	pool.register(|| protocol.Packet(&packets_422.FilterTextPacket{}))
	pool.register(|| protocol.Packet(&packets_291.GameRulesChangedPacket{}))
	pool.register(|| protocol.Packet(&packets_554.GameTestRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_554.GameTestResultsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.GuiDataPickItemPacket{}))
	pool.register(|| protocol.Packet(&packets_465.HurtArmorPacket{}))
	pool.register(|| protocol.Packet(&packets_388.InteractPacket{}))
	pool.register(|| protocol.Packet(&packets_407.InventoryContentPacket{}))
	pool.register(|| protocol.Packet(&packets_431.InventorySlotPacket{}))
	pool.register(|| protocol.Packet(&packets_431.InventoryTransactionPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ItemComponentPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ItemFrameDropItemPacket{}))
	pool.register(|| protocol.Packet(&packets_407.ItemStackRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ItemStackResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_291.LabTablePacket{}))
	pool.register(|| protocol.Packet(&packets_527.LessonProgressPacket{}))
	pool.register(|| protocol.Packet(&packets_486.LevelChunkPacket{}))
	pool.register(|| protocol.Packet(&packets.LevelEventGenericPacket{}))
	pool.register(|| protocol.Packet(&packets.LevelEventPacket{}))
	pool.register(|| protocol.Packet(&packets.LevelSoundEvent1Packet{}))
	pool.register(|| protocol.Packet(&packets.LevelSoundEvent2Packet{}))
	pool.register(|| protocol.Packet(&packets.LevelSoundEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.LoginPacket{}))
	pool.register(|| protocol.Packet(&packets_354.MapCreateLockedCopyPacket{}))
	pool.register(|| protocol.Packet(&packets_544.MapInfoRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_431.MobArmorEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_291.MobEffectPacket{}))
	pool.register(|| protocol.Packet(&packets_431.MobEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ModalFormRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_544.ModalFormResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_419.MotionPredictionHintsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.MoveEntityAbsolutePacket{}))
	pool.register(|| protocol.Packet(&packets_419.MoveEntityDeltaPacket{}))
	pool.register(|| protocol.Packet(&packets_419.MovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_388.MultiplayerSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_544.NetworkChunkPublisherUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets_554.NetworkSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_332.NetworkStackLatencyPacket{}))
	pool.register(|| protocol.Packet(&packets_448.NpcDialoguePacket{}))
	pool.register(|| protocol.Packet(&packets_448.NpcRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_354.OnScreenTextureAnimationPacket{}))
	pool.register(|| protocol.Packet(&packets_582.OpenSignPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PacketViolationWarningPacket{}))
	pool.register(|| protocol.Packet(&packets_471.PhotoInfoRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_465.PhotoTransferPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlaySoundPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlayStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_527.PlayerActionPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PlayerArmorDamagePacket{}))
	pool.register(|| protocol.Packet(&packets_575.PlayerAuthInputPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PlayerEnchantOptionsPacket{}))
	pool.register(|| protocol.Packet(&packets_419.PlayerFogPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlayerHotbarPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlayerInputPacket{}))
	pool.register(|| protocol.Packet(&packets_568.PlayerListPacket{}))
	pool.register(|| protocol.Packet(&packets_390.PlayerSkinPacket{}))
	pool.register(|| protocol.Packet(&packets_486.PlayerStartItemCooldownPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PositionTrackingDBClientRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PositionTrackingDBServerBroadcastPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PurchaseReceiptPacket{}))
	pool.register(|| protocol.Packet(&packets_618.RefreshEntitlementsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.RemoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_291.RemoveObjectivePacket{}))
	pool.register(|| protocol.Packet(&packets_503.RemoveVolumeEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_527.RequestAbilityPacket{}))
	pool.register(|| protocol.Packet(&packets_582.RequestChunkRadiusPacket{}))
	pool.register(|| protocol.Packet(&packets_554.RequestNetworkSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_527.RequestPermissionsPacket{}))
	pool.register(|| protocol.Packet(&packets_388.ResourcePackChunkDataPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ResourcePackChunkRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ResourcePackClientResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_388.ResourcePackDataInfoPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ResourcePackStackPacket{}))
	pool.register(|| protocol.Packet(&packets_618.ResourcePacksInfoPacket{}))
	pool.register(|| protocol.Packet(&packets_388.RespawnPacket{}))
	pool.register(|| protocol.Packet(&packets_291.RiderJumpPacket{}))
	pool.register(|| protocol.Packet(&packets_486.ScriptMessagePacket{}))
	pool.register(|| protocol.Packet(&packets.ServerPlayerPostMovePositionPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ServerSettingsRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ServerSettingsResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_554.ServerStatsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ServerToClientHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetCommandsEnabledPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetDefaultGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetDifficultyPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetDisplayObjectivePacket{}))
	pool.register(|| protocol.Packet(&packets_557.SetEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_407.SetEntityLinkPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetEntityMotionPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetHealthPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetLastHurtByPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetLocalPlayerAsInitializedPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetPlayerGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets.SetPlayerInventoryOptionsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetScorePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetScoreboardIdentityPacket{}))
	pool.register(|| protocol.Packet(&packets_407.SetSpawnPositionPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetTimePacket{}))
	pool.register(|| protocol.Packet(&packets_448.SetTitlePacket{}))
	pool.register(|| protocol.Packet(&packets_388.SettingsCommandPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ShowCreditsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ShowProfilePacket{}))
	pool.register(|| protocol.Packet(&packets.ShowStoreOfferPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SimpleEventPacket{}))
	pool.register(|| protocol.Packet(&packets_448.SimulationTypePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SpawnExperienceOrbPacket{}))
	pool.register(|| protocol.Packet(&packets_503.SpawnParticleEffectPacket{}))
	pool.register(|| protocol.Packet(&packets_589.StartGamePacket{}))
	pool.register(|| protocol.Packet(&packets_291.StopSoundPacket{}))
	pool.register(|| protocol.Packet(&packets_554.StructureBlockUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets_503.StructureTemplateDataRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_388.StructureTemplateDataResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_486.SubChunkPacket{}))
	pool.register(|| protocol.Packet(&packets_486.SubChunkRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SubClientLoginPacket{}))
	pool.register(|| protocol.Packet(&packets_440.SyncEntityPropertyPacket{}))
	pool.register(|| protocol.Packet(&packets_291.TakeItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_554.TextPacket{}))
	pool.register(|| protocol.Packet(&packets_388.TickSyncPacket{}))
	pool.register(|| protocol.Packet(&packets_503.TickingAreasLoadStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_527.ToastRequestPacket{}))
	pool.register(|| protocol.Packet(&packets.ToggleCrafterSlotRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.TransferPacket{}))
	pool.register(|| protocol.Packet(&packets_582.TrimDataPacket{}))
	pool.register(|| protocol.Packet(&packets_589.UnlockedRecipesPacket{}))
	pool.register(|| protocol.Packet(&packets_534.UpdateAbilitiesPacket{}))
	pool.register(|| protocol.Packet(&packets_534.UpdateAdventureSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_544.UpdateAttributesPacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_361.UpdateBlockPropertiesPacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateBlockSyncedPacket{}))
	pool.register(|| protocol.Packet(&packets_560.UpdateClientInputLocksPacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateEquipPacket{}))
	pool.register(|| protocol.Packet(&packets_407.UpdatePlayerGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateSoftEnumPacket{}))
	pool.register(|| protocol.Packet(&packets_465.UpdateSubChunkBlocksPacket{}))
	pool.register(|| protocol.Packet(&packets_354.UpdateTradePacket{}))
	return pool
}
