module v84

import protocol
import protocol.version.v84.packets
import protocol.version.v81.packets as packets_81

pub fn new_pool() protocol.PacketPool {
	mut pool := protocol.new_empty_pool()
	pool.register(|| protocol.Packet(&packets_81.LoginPacket{}))
	pool.register(|| protocol.Packet(&packets_81.PlayStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_81.DisconnectPacket{}))
	pool.register(|| protocol.Packet(&packets_81.TextPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetTimePacket{}))
	pool.register(|| protocol.Packet(&packets_81.StartGamePacket{}))
	pool.register(|| protocol.Packet(&packets_81.AddPlayerPacket{}))
	pool.register(|| protocol.Packet(&packets.AddEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_81.RemoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_81.AddItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_81.TakeItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets.MoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_81.MovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_81.RemoveBlockPacket{}))
	pool.register(|| protocol.Packet(&packets.UpdateBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_81.AddPaintingPacket{}))
	pool.register(|| protocol.Packet(&packets_81.ExplodePacket{}))
	pool.register(|| protocol.Packet(&packets_81.LevelEventPacket{}))
	pool.register(|| protocol.Packet(&packets_81.BlockEventPacket{}))
	pool.register(|| protocol.Packet(&packets_81.EntityEventPacket{}))
	pool.register(|| protocol.Packet(&packets_81.MobEffectPacket{}))
	pool.register(|| protocol.Packet(&packets_81.UpdateAttributesPacket{}))
	pool.register(|| protocol.Packet(&packets_81.MobEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_81.MobArmorEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_81.InteractPacket{}))
	pool.register(|| protocol.Packet(&packets_81.UseItemPacket{}))
	pool.register(|| protocol.Packet(&packets_81.PlayerActionPacket{}))
	pool.register(|| protocol.Packet(&packets_81.HurtArmorPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetEntityMotionPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetEntityLinkPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetHealthPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetSpawnPositionPacket{}))
	pool.register(|| protocol.Packet(&packets_81.AnimatePacket{}))
	pool.register(|| protocol.Packet(&packets_81.RespawnPacket{}))
	pool.register(|| protocol.Packet(&packets_81.DropItemPacket{}))
	pool.register(|| protocol.Packet(&packets_81.ContainerOpenPacket{}))
	pool.register(|| protocol.Packet(&packets_81.ContainerClosePacket{}))
	pool.register(|| protocol.Packet(&packets_81.ContainerSetSlotPacket{}))
	pool.register(|| protocol.Packet(&packets_81.ContainerSetDataPacket{}))
	pool.register(|| protocol.Packet(&packets_81.ContainerSetContentPacket{}))
	pool.register(|| protocol.Packet(&packets_81.CraftingDataPacket{}))
	pool.register(|| protocol.Packet(&packets_81.CraftingEventPacket{}))
	pool.register(|| protocol.Packet(&packets_81.AdventureSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_81.BlockEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets.ChangeDimensionPacket{}))
	pool.register(|| protocol.Packet(&packets_81.FullChunkDataPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetDifficultyPacket{}))
	pool.register(|| protocol.Packet(&packets_81.SetPlayerGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets_81.PlayerListPacket{}))
	pool.register(|| protocol.Packet(&packets_81.RequestChunkRadiusPacket{}))
	pool.register(|| protocol.Packet(&packets_81.ChunkRadiusUpdatedPacket{}))
	return pool
}
