module v428

import protocol
import protocol.version
import protocol.version.v291.packets as packets_291
import protocol.version.v313.packets as packets_313
import protocol.version.v332.packets as packets_332
import protocol.version.v340.packets as packets_340
import protocol.version.v354.packets as packets_354
import protocol.version.v361.packets as packets_361
import protocol.version.v388.packets as packets_388
import protocol.version.v389.packets as packets_389
import protocol.version.v390.packets as packets_390
import protocol.version.v407.packets as packets_407
import protocol.version.v419.packets as packets_419
import protocol.version.v422.packets as packets_422
import protocol.version.v428.packets

pub const proto_version = version.ProtoVersion.v428

pub fn new_pool() protocol.PacketPool {
	mut pool := protocol.new_empty_pool()
	pool.register(|| protocol.Packet(&packets_291.AddBehaviorTreePacket{}))
	pool.register(|| protocol.Packet(&packets.AddEntityPacket{}))
	pool.register(|| protocol.Packet(&packets.AddItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_361.AddPaintingPacket{}))
	pool.register(|| protocol.Packet(&packets_388.AddPlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_291.AdventureSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_419.AnimateEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_291.AnimatePacket{}))
	pool.register(|| protocol.Packet(&packets_388.AnvilDamagePacket{}))
	pool.register(|| protocol.Packet(&packets_291.AutomationClientConnectPacket{}))
	pool.register(|| protocol.Packet(&packets.AvailableCommandsPacket{}))
	pool.register(|| protocol.Packet(&packets_313.AvailableEntityIdentifiersPacket{}))
	pool.register(|| protocol.Packet(&packets_313.BiomeDefinitionListPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BlockEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BlockEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BlockPickRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BookEditPacket{}))
	pool.register(|| protocol.Packet(&packets_291.BossEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.CameraPacket{}))
	pool.register(|| protocol.Packet(&packets.CameraShakePacket{}))
	pool.register(|| protocol.Packet(&packets_291.ChangeDimensionPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ChunkRadiusUpdatedPacket{}))
	pool.register(|| protocol.Packet(&packets_361.ClientCacheBlobStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_361.ClientCacheMissResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_361.ClientCacheStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ClientToServerHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets.ClientboundDebugRendererPacket{}))
	pool.register(|| protocol.Packet(&packets_354.ClientboundMapItemDataPacket{}))
	pool.register(|| protocol.Packet(&packets_407.CodeBuilderPacket{}))
	pool.register(|| protocol.Packet(&packets_361.CommandBlockUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets_291.CommandOutputPacket{}))
	pool.register(|| protocol.Packet(&packets_291.CommandRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_388.CompletedUsingItemPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ContainerClosePacket{}))
	pool.register(|| protocol.Packet(&packets_291.ContainerOpenPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ContainerSetDataPacket{}))
	pool.register(|| protocol.Packet(&packets_419.CorrectPlayerMovePredictionPacket{}))
	pool.register(|| protocol.Packet(&packets_407.CraftingDataPacket{}))
	pool.register(|| protocol.Packet(&packets_291.CraftingEventPacket{}))
	pool.register(|| protocol.Packet(&packets_407.CreativeContentPacket{}))
	pool.register(|| protocol.Packet(&packets_407.DebugInfoPacket{}))
	pool.register(|| protocol.Packet(&packets_291.DisconnectPacket{}))
	pool.register(|| protocol.Packet(&packets_407.EducationSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_407.EmoteListPacket{}))
	pool.register(|| protocol.Packet(&packets_388.EmotePacket{}))
	pool.register(|| protocol.Packet(&packets_407.EntityEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.EntityFallPacket{}))
	pool.register(|| protocol.Packet(&packets_291.EntityPickRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_389.EventPacket{}))
	pool.register(|| protocol.Packet(&packets_422.FilterTextPacket{}))
	pool.register(|| protocol.Packet(&packets_291.GameRulesChangedPacket{}))
	pool.register(|| protocol.Packet(&packets_291.GuiDataPickItemPacket{}))
	pool.register(|| protocol.Packet(&packets_407.HurtArmorPacket{}))
	pool.register(|| protocol.Packet(&packets_388.InteractPacket{}))
	pool.register(|| protocol.Packet(&packets_407.InventoryContentPacket{}))
	pool.register(|| protocol.Packet(&packets_407.InventorySlotPacket{}))
	pool.register(|| protocol.Packet(&packets_407.InventoryTransactionPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ItemComponentPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ItemFrameDropItemPacket{}))
	pool.register(|| protocol.Packet(&packets_407.ItemStackRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ItemStackResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_291.LabTablePacket{}))
	pool.register(|| protocol.Packet(&packets_361.LevelChunkPacket{}))
	pool.register(|| protocol.Packet(&packets.LevelEventGenericPacket{}))
	pool.register(|| protocol.Packet(&packets.LevelEventPacket{}))
	pool.register(|| protocol.Packet(&packets.LevelSoundEvent1Packet{}))
	pool.register(|| protocol.Packet(&packets.LevelSoundEvent2Packet{}))
	pool.register(|| protocol.Packet(&packets.LevelSoundEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.LoginPacket{}))
	pool.register(|| protocol.Packet(&packets_354.MapCreateLockedCopyPacket{}))
	pool.register(|| protocol.Packet(&packets_291.MapInfoRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_340.MobArmorEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_291.MobEffectPacket{}))
	pool.register(|| protocol.Packet(&packets_340.MobEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ModalFormRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ModalFormResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_419.MotionPredictionHintsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.MoveEntityAbsolutePacket{}))
	pool.register(|| protocol.Packet(&packets_419.MoveEntityDeltaPacket{}))
	pool.register(|| protocol.Packet(&packets_419.MovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_388.MultiplayerSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_313.NetworkChunkPublisherUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets_388.NetworkSettingsPacket{}))
	pool.register(|| protocol.Packet(&packets_332.NetworkStackLatencyPacket{}))
	pool.register(|| protocol.Packet(&packets_291.NpcRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_354.OnScreenTextureAnimationPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PacketViolationWarningPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PhotoTransferPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlaySoundPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlayStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlayerActionPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PlayerArmorDamagePacket{}))
	pool.register(|| protocol.Packet(&packets.PlayerAuthInputPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PlayerEnchantOptionsPacket{}))
	pool.register(|| protocol.Packet(&packets_419.PlayerFogPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlayerHotbarPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PlayerInputPacket{}))
	pool.register(|| protocol.Packet(&packets.PlayerListPacket{}))
	pool.register(|| protocol.Packet(&packets_390.PlayerSkinPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PositionTrackingDBClientRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_407.PositionTrackingDBServerBroadcastPacket{}))
	pool.register(|| protocol.Packet(&packets_291.PurchaseReceiptPacket{}))
	pool.register(|| protocol.Packet(&packets_291.RemoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_291.RemoveObjectivePacket{}))
	pool.register(|| protocol.Packet(&packets_291.RequestChunkRadiusPacket{}))
	pool.register(|| protocol.Packet(&packets_388.ResourcePackChunkDataPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ResourcePackChunkRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ResourcePackClientResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_388.ResourcePackDataInfoPacket{}))
	pool.register(|| protocol.Packet(&packets_419.ResourcePackStackPacket{}))
	pool.register(|| protocol.Packet(&packets_422.ResourcePacksInfoPacket{}))
	pool.register(|| protocol.Packet(&packets_388.RespawnPacket{}))
	pool.register(|| protocol.Packet(&packets_291.RiderJumpPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ScriptCustomEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ServerSettingsRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ServerSettingsResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_291.ServerToClientHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetCommandsEnabledPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetDefaultGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetDifficultyPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetDisplayObjectivePacket{}))
	pool.register(|| protocol.Packet(&packets_419.SetEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets_407.SetEntityLinkPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetEntityMotionPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetHealthPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetLastHurtByPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetLocalPlayerAsInitializedPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetPlayerGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetScorePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetScoreboardIdentityPacket{}))
	pool.register(|| protocol.Packet(&packets_407.SetSpawnPositionPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetTimePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SetTitlePacket{}))
	pool.register(|| protocol.Packet(&packets_388.SettingsCommandPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ShowCreditsPacket{}))
	pool.register(|| protocol.Packet(&packets_291.ShowProfilePacket{}))
	pool.register(|| protocol.Packet(&packets_291.ShowStoreOfferPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SimpleEventPacket{}))
	pool.register(|| protocol.Packet(&packets_291.SpawnExperienceOrbPacket{}))
	pool.register(|| protocol.Packet(&packets_332.SpawnParticleEffectPacket{}))
	pool.register(|| protocol.Packet(&packets.StartGamePacket{}))
	pool.register(|| protocol.Packet(&packets_291.StopSoundPacket{}))
	pool.register(|| protocol.Packet(&packets_388.StructureBlockUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets_388.StructureTemplateDataRequestPacket{}))
	pool.register(|| protocol.Packet(&packets_388.StructureTemplateDataResponsePacket{}))
	pool.register(|| protocol.Packet(&packets_291.SubClientLoginPacket{}))
	pool.register(|| protocol.Packet(&packets_291.TakeItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_332.TextPacket{}))
	pool.register(|| protocol.Packet(&packets_388.TickSyncPacket{}))
	pool.register(|| protocol.Packet(&packets_291.TransferPacket{}))
	pool.register(|| protocol.Packet(&packets_419.UpdateAttributesPacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_361.UpdateBlockPropertiesPacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateBlockSyncedPacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateEquipPacket{}))
	pool.register(|| protocol.Packet(&packets_407.UpdatePlayerGameTypePacket{}))
	pool.register(|| protocol.Packet(&packets_291.UpdateSoftEnumPacket{}))
	pool.register(|| protocol.Packet(&packets_354.UpdateTradePacket{}))
	return pool
}
