module v11

import protocol
import protocol.version.v11.packets
import protocol.version.v9.packets as packets_9

pub fn new_pool() protocol.PacketPool {
	mut pool := protocol.new_empty_pool()
	pool.register(|| protocol.Packet(&packets.PingPacket{}))
	pool.register(|| protocol.Packet(&packets.PongPacket{}))
	pool.register(|| protocol.Packet(&packets_9.ClientConnectPacket{}))
	pool.register(|| protocol.Packet(&packets.ServerHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets_9.ClientHandshakePacket{}))
	pool.register(|| protocol.Packet(&packets.ServerFullPacket{}))
	pool.register(|| protocol.Packet(&packets_9.DisconnectPacket{}))
	pool.register(|| protocol.Packet(&packets.BannedPacket{}))
	pool.register(|| protocol.Packet(&packets.LoginPacket{}))
	pool.register(|| protocol.Packet(&packets_9.PlayStatusPacket{}))
	pool.register(|| protocol.Packet(&packets_9.ReadyPacket{}))
	pool.register(|| protocol.Packet(&packets_9.MessagePacket{}))
	pool.register(|| protocol.Packet(&packets.SetTimePacket{}))
	pool.register(|| protocol.Packet(&packets_9.StartGamePacket{}))
	pool.register(|| protocol.Packet(&packets_9.AddMobPacket{}))
	pool.register(|| protocol.Packet(&packets_9.AddPlayerPacket{}))
	pool.register(|| protocol.Packet(&packets.RemovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets.AddEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.RemoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.AddItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets.TakeItemEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.MoveEntityPacket{}))
	pool.register(|| protocol.Packet(&packets_9.MoveEntityPosRotPacket{}))
	pool.register(|| protocol.Packet(&packets_9.MovePlayerPacket{}))
	pool.register(|| protocol.Packet(&packets_9.PlaceBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_9.RemoveBlockPacket{}))
	pool.register(|| protocol.Packet(&packets_9.UpdateBlockPacket{}))
	pool.register(|| protocol.Packet(&packets.AddPaintingPacket{}))
	pool.register(|| protocol.Packet(&packets.ExplosionPacket{}))
	pool.register(|| protocol.Packet(&packets.LevelEventPacket{}))
	pool.register(|| protocol.Packet(&packets.EntityEventPacket{}))
	pool.register(|| protocol.Packet(&packets_9.RequestChunkPacket{}))
	pool.register(|| protocol.Packet(&packets_9.ChunkDataPacket{}))
	pool.register(|| protocol.Packet(&packets.PlayerEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets.PlayerArmorEquipmentPacket{}))
	pool.register(|| protocol.Packet(&packets.InteractPacket{}))
	pool.register(|| protocol.Packet(&packets.UseItemPacket{}))
	pool.register(|| protocol.Packet(&packets.PlayerActionPacket{}))
	pool.register(|| protocol.Packet(&packets.HurtArmorPacket{}))
	pool.register(|| protocol.Packet(&packets.SetEntityDataPacket{}))
	pool.register(|| protocol.Packet(&packets.SetEntityMotionPacket{}))
	pool.register(|| protocol.Packet(&packets.SetHealthPacket{}))
	pool.register(|| protocol.Packet(&packets.SetSpawnPositionPacket{}))
	pool.register(|| protocol.Packet(&packets.AnimatePacket{}))
	pool.register(|| protocol.Packet(&packets.RespawnPacket{}))
	pool.register(|| protocol.Packet(&packets.SendInventoryPacket{}))
	pool.register(|| protocol.Packet(&packets.DropItemPacket{}))
	pool.register(|| protocol.Packet(&packets.ContainerOpenPacket{}))
	pool.register(|| protocol.Packet(&packets.ContainerClosePacket{}))
	pool.register(|| protocol.Packet(&packets.ContainerSetSlotPacket{}))
	pool.register(|| protocol.Packet(&packets.ContainerSetDataPacket{}))
	pool.register(|| protocol.Packet(&packets.ContainerSetContentPacket{}))
	pool.register(|| protocol.Packet(&packets.ClientMessagePacket{}))
	pool.register(|| protocol.Packet(&packets.SignUpdatePacket{}))
	pool.register(|| protocol.Packet(&packets.AdventureSettingsPacket{}))
	return pool
}
